remote_theme: broccolini/athena
title: Athena Jekyll Theme
description: A simple and elegant theme for Jekyll and GitHub Pages.
github_repo: athena
github_username: broccolini
social_link: twitter
social_username: broccolini
theme_color: light
baseurl: /taciturn_captain
