remote_theme: broccolini/athena
title: Stastic Website Editor
description: Stastic is the easiest way to get started to manage a static website
github_repo: test
github_username: internet-de-france
social_link: 'https://twitter.com/lexoyo'
social_username: broccolini
theme_color: light
baseurl: /taciturn_captain
