remote_theme: broccolini/athena
title: Stastic Website Editor
description: Stastic is the easiest way to get started to manage a static website
github_repo: athena
github_username: broccolini
social_link: twitter
social_username: broccolini
theme_color: light
baseurl: /taciturn_captain
